name: PR Validation


on:
  pull_request:
    branches:
      - develop  # This ensures the workflow runs only on pull requests targeting 'develop'

jobs:
  linting:
    name: Linting Job
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2
        
      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # You can change this to the version you need

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install
          
      # Lint HTML files using HTMLHint
      - name: Lint HTML files
        run: npx htmlhint "**/*.html"

      # Lint CSS files using Stylelint
      - name: Lint CSS files
        run: npx stylelint "**/*.css"

  build:
    name: Build Job
    runs-on: ubuntu-latest
    needs: linting  # This ensures 'build' job runs only after the 'linting' job passes

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2
        
      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Build the static website using Parcel
      - name: Build the website using Parcel
        run: |
          npx parcel build src/index.html --no-minify --no-source-maps

